# Generated by Django 5.2.12 on 2026-03-31 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='editorial_api',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='portada_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='titulo_api',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
